# Generated by Django 3.2.6 on 2021-08-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_news_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_post',
            name='date',
        ),
        migrations.AddField(
            model_name='news_post',
            name='day',
            field=models.IntegerField(default='0', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news_post',
            name='month',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
